### ISSUE TITLE
请依次点击后面不出来文字呢...

### ISSUE THREAD

**Issue by liquan137** [hooray/vue-clicaptcha#1]
![微信截图_20190314144110](https://user-images.githubusercontent.com/40263384/54336516-3bc73e80-4667-11e9-8a5f-c0a4d1dd4bac.png)
没有那个文字顺序的提示，
![微信截图_20190314144203](https://user-images.githubusercontent.com/40263384/54336555-5b5e6700-4667-11e9-8056-c49d6a6adc16.png)

**Comment by hooray** [comment]
@liquan137 检查下cookie里是否有`clicaptcha_text`字段的信息

**Comment by luuuuuuuuu** [comment]
cookie取不到内容 怎么办

**Comment by hooray** [comment]
@luuuuuuuuu 确保没有跨域，其次检查后端生成图片的同时是否正常写入cookie，可通过开发者工具检查，读不到无非这两种情况，要么跨域读不到，要么cookie就没有写入成功，没有数据

**Comment by luuuuuuuuu** [comment]
多谢 , 经过验证 是后端写入cookie时出错了,  后端设置cookie, 需要添加 domian 和path参数
